name: hello world workflow
on:
  push:
    branches:
      - main
      - develop
      - 'release/*''
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello Step
        run: |
          echo "Hello to Git Hub actions"
          docker ps
          ls -ltra

    
