name: hello world workflow
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello Step
        run: |
          echo "Hello to Git Hub actions"
          docker ps
          ls -ltra
